### ISSUE TITLE
Fix state plugins missing

### ISSUE THREAD

**Issue by Fizzadar** [Oxygem/canaryd#2]
```py
canaryctl state meta
Traceback (most recent call last):
  File "/usr/local/bin/canaryctl", line 4, in <module>
    from canaryd.ctl import __main__  # noqa
  File "/usr/local/lib/python2.7/site-packages/canaryd/ctl/__main__.py", line 14, in <module>
    main()
  File "/usr/local/lib/python2.7/site-packages/canaryd/packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/canaryd/packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/canaryd/packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/canaryd/packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/canaryd/packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/canaryd/ctl/__init__.py", line 149, in state
    raise TypeError('Invalid plugin: {0}'.format(plugin))
TypeError: Invalid plugin: meta
```

**Comment by Fizzadar** [comment]
Closed @ https://github.com/Oxygem/canaryd/commit/d760783badd0c3b38300388cd86dafc025744777
