### ISSUE TITLE
Handle null/non-iterable docker commands

### ISSUE THREAD

**Issue by Fizzadar** [Oxygem/canaryd#46]
```Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/canaryd/plugin.py", line 364, in get_plugin_state
    state = plugin.get_state(settings)
  File "/usr/local/lib/python2.7/dist-packages/canaryd/plugins/containers.py", line 67, in get_state
    containers.update(func(timeout=timeout))
  File "/usr/local/lib/python2.7/dist-packages/canaryd/plugins/containers_util.py", line 26, in get_docker_containers
    'command': ' '.join(container['Config']['Cmd']),
TypeError: can only join an iterable```

**Comment by Fizzadar** [comment]
https://github.com/Oxygem/canaryd/commit/6bb7f1c133748b09a89049fc76233d62bc67095b
